# Generated by Django 4.2.13 on 2024-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, verbose_name='Код товара')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('product_type', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('product_brand', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('product_series', models.CharField(blank=True, max_length=255, verbose_name='Серия')),
                ('product_model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('product_partnumber', models.CharField(blank=True, max_length=255, verbose_name='Partnumber')),
            ],
        ),
    ]
