# Generated by Django 4.2.13 on 2024-06-13 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, verbose_name='Код товара')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('product_type', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('product_brand', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('product_series', models.CharField(blank=True, max_length=255, verbose_name='Серия')),
                ('product_model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('product_partnumber', models.CharField(blank=True, max_length=255, verbose_name='Partnumber')),
            ],
        ),
        migrations.CreateModel(
            name='GPTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ошибка', 'Ошибка'), ('Обрабатывается', 'Обрабатывается'), ('Успешно', 'Успешно')], verbose_name='Статус')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Ответ GPT')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpt_requests', to=settings.AUTH_USER_MODEL)),
                ('user_product_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpt_requests', to='app.userproductdata')),
            ],
        ),
    ]
