# Generated by Django 4.2.13 on 2024-06-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ошибка', 'Ошибка'), ('Обрабатывается', 'Обрабатывается'), ('Успешно', 'Успешно')], verbose_name='Статус')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Ответ GPT')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpt_requests', to=settings.AUTH_USER_MODEL)),
                ('user_product_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpt_requests', to='app.userproductdata')),
            ],
        ),
    ]
